In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/occurrences.csv")

print(df.shape)
df.head()

(37200, 24)

,occurrence_no,record_type,reid_no,flags,collection_no,identified_name,identified_rank,identified_no,difference,accepted_name,...,max_ma,min_ma,reference_no,lng,lat,cx_int_no,environment,formation,geological_group,member
0,95928,occ,NaN,NaN,7204,Marginalosia planata,species,137248.0,NaN,Marginalosia planata,...,254.14,251.902,440,173.266663,-41.299999,715,NaN,Stephens,NaN,NaN
1,95930,occ,NaN,NaN,7204,Terrakea sp.,genus,NaN,NaN,Terrakea,...,254.14,251.902,440,173.266663,-41.299999,715,NaN,Stephens,NaN,NaN
2,95932,occ,NaN,NaN,7204,Spiriferella sp.,genus,29639.0,NaN,Spiriferella,...,254.14,251.902,440,173.266663,-41.299999,715,NaN,Stephens,NaN,NaN
3,95933,occ,NaN,NaN,7204,Martinia sp.,genus,NaN,NaN,Martinia,...,254.14,251.902,440,173.266663,-41.299999,715,NaN,Stephens,NaN,NaN
4,95934,occ,NaN,NaN,7204,Tomiopsis furca,genus,NaN,species not entered,Tomiopsis,...,254.14,251.902,440,173.266663,-41.299999,715,NaN,Stephens,NaN,NaN

In [2]:
df.isnull().sum().sort_values(ascending=False).head(20)

flags               37200
reid_no             36258
late_interval       34437
geological_group    34166
difference          29500
member              29134
identified_no       23105
formation            7398
environment           494
min_ma                  0
cx_int_no               0
lat                     0
lng                     0
reference_no            0
occurrence_no           0
max_ma                  0
record_type             0
accepted_no             0
accepted_rank           0
accepted_name           0
dtype: int64

In [3]:
df["early_interval"].value_counts()

Changhsingian      10046
Smithian            4618
Griesbachian        4122
Anisian             3739
Spathian            3322
Pelsonian           3314
Illyrian            2760
Dienerian           1517
Olenekian           1185
Bithynian            950
Aegean               557
Middle Triassic      416
Induan               334
Early Triassic       319
Wuchiapingian          1
Name: early_interval, dtype: int64

In [5]:
import pandas as pd

df = pd.read_csv("../data/raw/occurrences.csv")

print(df.shape)

(37200, 24)

In [6]:
cols = [
    "accepted_name",
    "early_interval",
    "late_interval",
    "collection_no",
    "environment",
    "formation",
    "lat",
    "lng",
    "max_ma",
    "min_ma"
]

clean = df[cols].copy()

clean.dropna(
    subset=[
        "accepted_name",
        "early_interval",
        "collection_no"
    ],
    inplace=True
)

print(clean.shape)

(37200, 10)

In [7]:
valid_intervals = [
    "Changhsingian",
    "Griesbachian",
    "Dienerian",
    "Smithian",
    "Spathian",
    "Aegean",
    "Bithynian",
    "Pelsonian",
    "Illyrian",
    "Anisian"
]

clean = clean[
    clean["early_interval"].isin(valid_intervals)
].copy()

print(clean.shape)

(34945, 10)

In [8]:
clean["early_interval"].value_counts()

Changhsingian    10046
Smithian          4618
Griesbachian      4122
Anisian           3739
Spathian          3322
Pelsonian         3314
Illyrian          2760
Dienerian         1517
Bithynian          950
Aegean             557
Name: early_interval, dtype: int64

In [9]:
interval_order = [
    "Changhsingian",
    "Griesbachian",
    "Dienerian",
    "Smithian",
    "Spathian",
    "Aegean",
    "Bithynian",
    "Pelsonian",
    "Illyrian",
    "Anisian"
]

richness = (
    clean.groupby("early_interval")
    ["accepted_name"]
    .nunique()
    .reindex(interval_order)
)

print(richness)

early_interval
Changhsingian    1901
Griesbachian      441
Dienerian         306
Smithian          806
Spathian          736
Aegean            261
Bithynian         317
Pelsonian         538
Illyrian          596
Anisian          1223
Name: accepted_name, dtype: int64

In [10]:
collections = (
    clean.groupby("early_interval")
    ["collection_no"]
    .nunique()
    .reindex(interval_order)
)

print(collections)

early_interval
Changhsingian    2126
Griesbachian     1282
Dienerian         620
Smithian         1153
Spathian          940
Aegean            209
Bithynian         304
Pelsonian         435
Illyrian          801
Anisian           903
Name: collection_no, dtype: int64

In [11]:
comparison = pd.DataFrame({
    "richness": richness,
    "collections": collections
})

print(comparison.corr())

             richness  collections
richness     1.000000     0.829275
collections  0.829275     1.000000

In [12]:
print("Shape:", clean.shape)
print("Unique genera:", clean["accepted_name"].nunique())

Shape: (34945, 10)
Unique genera: 5344

In [13]:
richness = clean.groupby(
    "early_interval"
)["accepted_name"].nunique()

print(richness)

early_interval
Aegean            261
Anisian          1223
Bithynian         317
Changhsingian    1901
Dienerian         306
Griesbachian      441
Illyrian          596
Pelsonian         538
Smithian          806
Spathian          736
Name: accepted_name, dtype: int64

In [14]:
collections = clean.groupby(
    "early_interval"
)["collection_no"].nunique()

print(collections)

early_interval
Aegean            209
Anisian           903
Bithynian         304
Changhsingian    2126
Dienerian         620
Griesbachian     1282
Illyrian          801
Pelsonian         435
Smithian         1153
Spathian          940
Name: collection_no, dtype: int64

In [15]:
comparison = pd.DataFrame({
    "richness": richness,
    "collections": collections
})

comparison.corr()

             richness  collections
richness     1.000000     0.829275
collections  0.829275     1.000000

In [16]:
clean.to_csv(
    "../data/processed/occurrences_clean.csv",
    index=False
)